vich_uploader:
    db_driver: orm 
    metadata:
        type: attribute
    mappings:
    
        image_upload:
            uri_prefix: /images/gifts
            upload_destination: '%kernel.project_dir%/public/images/gifts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer